
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javapub-flowable2?serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: true
server:
  port: 8081
